/**
 * dsh-lan-url — local helper (our own code, no third-party package).
 *
 * Why: the browser entry URL carries a per-process random launch token that
 * lives only in memory (`dsh-client-connection/lib/index.js` keeps it in a
 * module-level WeakMap keyed by the root context and mints it with
 * `randomBytes`), and `dsh web` prints it exactly once, on its own stdout. If
 * that console line scrolls away, the only remaining ways to reach the GUI from
 * another device are re-reading the terminal or restarting the process.
 *
 * What this does: calls the same public first-party API `dsh-web-app` itself
 * calls when it prints its `dsh web:` line —
 *
 *   ctx.connection.authenticatedUrl(`http://<host>:<port>`)
 *
 * — for loopback plus every non-internal IPv4 address, and writes one URL per
 * line to `$DSH_HOME/web-urls.txt`. Nothing is minted, derived, or bypassed:
 * the token comes from the live service.
 *
 * The token survives Connection reloads (the WeakMap is keyed by the root
 * context) but is regenerated by a process restart, so the file is rewritten
 * on every activation.
 *
 * !! The output file contains live credentials. Delete it when it is not
 * !! needed, and remove this row (see the profile's cordis.patch.yml) to stop
 * !! writing it.
 */

import { networkInterfaces, homedir } from 'node:os'
import { join } from 'node:path'
import { writeFileSync } from 'node:fs'

/** Stable Cordis plugin name. */
const name = 'lan-url'

/** Both services must exist before the token and the listening port are readable. */
const inject = ['connection', 'webServer']

/** Loopback first, then every non-internal IPv4 literal (LAN, VPN, VM nets). */
function candidateHosts() {
  const external = Object.values(networkInterfaces())
    .flat()
    .filter((iface) => iface !== undefined && iface.family === 'IPv4' && !iface.internal)
    .map((iface) => iface.address)
  return ['127.0.0.1', ...new Set(external)]
}

/**
 * Write the token-bearing URLs for this process.
 * @param ctx - plugin context carrying `connection` and `webServer`.
 */
function apply(ctx) {
  const port = ctx.webServer.port
  if (port === undefined) {
    ctx.logger?.warn?.('lan-url: webServer has no listening port yet; nothing written')
    return
  }
  const urls = candidateHosts().map((host) => ctx.connection.authenticatedUrl(`http://${host}:${String(port)}`))
  const home = process.env.DSH_HOME ?? join(homedir(), '.dsh')
  const file = join(home, 'web-urls.txt')
  writeFileSync(file, `${urls.join('\n')}\n`, 'utf8')
  ctx.logger?.info?.(`lan-url: wrote ${String(urls.length)} token-bearing URLs to ${file}`)
}

export { apply, candidateHosts, inject, name }
